# This rule is not used by the project infraagent itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over core.infraagent.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: infraagent
    app.kubernetes.io/managed-by: kustomize
  name: agentenvironment-admin-role
rules:
- apiGroups:
  - core.infraagent.io
  resources:
  - agentenvironments
  verbs:
  - '*'
- apiGroups:
  - core.infraagent.io
  resources:
  - agentenvironments/status
  verbs:
  - get
