---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - legator.io
  resources:
  - legatoragents
  - legatorenvironments
  - legatorruns
  - modeltierconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - legator.io
  resources:
  - legatoragents/finalizers
  - legatorenvironments/finalizers
  - legatorruns/finalizers
  - modeltierconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - legator.io
  resources:
  - legatoragents/status
  - legatorenvironments/status
  - legatorruns/status
  - modeltierconfigs/status
  verbs:
  - get
  - patch
  - update
