# This rule is not used by the project legator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the legator.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: legator
    app.kubernetes.io/managed-by: kustomize
  name: userpolicy-editor-role
rules:
- apiGroups:
  - legator.io
  resources:
  - userpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - legator.io
  resources:
  - userpolicies/status
  verbs:
  - get
