apiVersion: core.infraagent.io/v1alpha1
kind: AgentRun
metadata:
  labels:
    app.kubernetes.io/name: infraagent
    app.kubernetes.io/managed-by: kustomize
  name: agentrun-sample
spec:
  # TODO(user): Add fields here
